### PR TITLE
Synchronize writes to influxdb

### LINKED ISSUE #78: Failed to send data from build to influxDB, when another build already sending data
image

### PR DESCRIPTION
**Pull request by jeffpearce**
Should fix #78

### CODE REVIEW

**Comment by krolol** [comment]
@jeffpearce, Can you provide estimates when the release will be done?

**Comment by jeffpearce** [comment]
@krolol I'm aiming for the end of the week.

**Comment by krolol** [comment]
@jeffpearce, we are waiting for a release, can you do it as soon as possible?

**Comment by jeffpearce** [comment]
Hi @krolol. I need to do some additional testing before I do a general release. Would an alpha release work for you? You’d need to use the experimental plugin repo to install

**Comment by krolol** [comment]
Hi @jeffpearce, we can wait for general release, if that takes not a lot of time

**Pull request merged**
